/*
 * Generated by scripts/sync-channels.mjs from the "agentcomms" field of each channel's package.json.
 * Run `pnpm sync:channels` after changing one; do not edit this file.
 */
import type { ChannelEntry } from './channel-manifest.ts';

/** The channels built into this release, by their word: a channel is a string, and these are the known ones. */
export type BuiltInChannel = 'core' | 'gmail' | 'resend' | 'slack' | 'whatsapp';

/** Every first-party channel, the core first: what core knows about each without installing it. */
export const CHANNEL_SNAPSHOT: readonly ChannelEntry[] = [
  {
    packageName: '@agentcomms/core',
    manifest: {
      contract: 1,
      channel: 'core',
      label: 'agentcomms (core)',
      binary: 'agentcomms',
      server: {
        defaultName: 'agentcomms',
        npxPackage: '@agentcomms/core',
        npxArgs: ['mcp'],
      },
      approve: 'agentcomms approve',
      skills: {
        prefix: 'comms-',
        contract: 'skills/_shared/contract-comms.md',
      },
    },
  },
  {
    packageName: '@agentcomms/gmail',
    manifest: {
      contract: 1,
      channel: 'gmail',
      label: 'Gmail',
      binary: 'agent-gmail',
      server: {
        defaultName: 'gmail',
        npxPackage: '@agentcomms/gmail-mcp',
        entryFiles: [['node_modules', '@agentcomms', 'gmail-mcp', 'dist', 'server.mjs']],
        bins: ['agent-gmail-mcp'],
      },
      accounts: {
        map: 'inboxes',
        noun: 'mailbox',
        modes: ['read', 'send'],
        guarantee: {
          ceiling: 'grant',
          floor: 'grant',
          why: 'A mailbox connected at the read tier holds only gmail.readonly, which Google will not send with. Every tier that can draft can also send, so above read it is the approval gate, not the grant, that stands between a draft and a sent message.',
        },
      },
      narrowing: [
        {
          option: 'inbox',
          flag: '--inbox',
          kind: 'pin',
        },
        {
          option: 'readOnly',
          flag: '--read-only',
          kind: 'switch',
        },
      ],
      rivals: {
        packages: [
          {
            name: '@artymclabin/gmail-mcp',
          },
          {
            name: '@gongrzhe/server-gmail-autoauth-mcp',
            unscoped: true,
          },
          {
            name: '@shinzolabs/gmail-mcp',
          },
        ],
      },
      hosts: ['accounts.google.com', 'oauth2.googleapis.com', 'gmail.googleapis.com', 'people.googleapis.com'],
      approve: 'agent-gmail approve',
      skills: {
        prefix: 'gmail-',
        contract: 'skills/_shared/contract-gmail.md',
      },
      approvalGrouping: 'draft',
      events: {
        types: ['gmail.message.received', 'gmail.message.sent', 'gmail.message.labelled'],
        minimumIntervalMs: 60000,
        access: {
          kind: 'oauth-user',
          requiredScopes: ['https://www.googleapis.com/auth/gmail.readonly'],
        },
      },
    },
  },
  {
    packageName: '@agentcomms/resend',
    manifest: {
      contract: 1,
      channel: 'resend',
      label: 'Resend',
      binary: 'agent-resend',
      server: {
        defaultName: 'resend',
        npxPackage: '@agentcomms/resend',
        npxArgs: ['mcp'],
      },
      accounts: {
        map: 'accounts',
        noun: 'account',
        modes: ['read', 'send'],
        guarantee: {
          ceiling: 'code',
          floor: 'code',
          why: "Resend has no read-only key, and a full-access key can also manage domains and keys: read mode, and send mode's limit to sending, are enforced by this package's own code. A sending-access key can only send, and Resend enforces that.",
        },
      },
      narrowing: [
        {
          option: 'account',
          flag: '--account',
          kind: 'pin',
        },
      ],
      rivals: {
        word: 'resend',
        can: 'send mail through Resend',
      },
      hosts: ['api.resend.com', 'inbound-cdn.resend.com'],
      approve: 'agent-resend approve',
      skills: {
        prefix: 'resend-',
        contract: 'skills/_shared/contract-resend.md',
      },
      approvalGrouping: 'draft',
      events: {
        types: ['resend.email.received', 'resend.email.status_changed'],
        minimumIntervalMs: 60000,
        access: {
          kind: 'resend-full-access',
        },
      },
    },
  },
  {
    packageName: '@agentcomms/slack',
    manifest: {
      contract: 1,
      channel: 'slack',
      label: 'Slack',
      binary: 'agent-slack',
      server: {
        defaultName: 'slack',
        npxPackage: '@agentcomms/slack',
        npxArgs: ['mcp'],
      },
      accounts: {
        map: 'accounts',
        noun: 'workspace',
        modes: ['read', 'send'],
        guarantee: {
          ceiling: 'grant',
          floor: 'grant',
          why: 'A workspace connected to read holds a user token with no posting scope, so Slack itself refuses to post with it; one connected to send holds the scopes its app declares and no more.',
        },
      },
      narrowing: [
        {
          option: 'workspace',
          flag: '--workspace',
          kind: 'pin',
        },
      ],
      rivals: {
        word: 'slack',
        can: 'post to Slack',
      },
      hosts: ['slack.com', 'files.slack.com'],
      approve: 'agent-slack approve',
      skills: {
        prefix: 'slack-',
        contract: 'skills/_shared/contract-slack.md',
      },
      approvalGrouping: 'draft-revision-digest',
      events: {
        types: ['slack.message.posted'],
        minimumIntervalMs: 60000,
        access: {
          kind: 'oauth-user',
          requiredScopes: ['channels:history', 'groups:history', 'im:history', 'mpim:history'],
        },
      },
    },
  },
  {
    packageName: '@agentcomms/whatsapp',
    manifest: {
      contract: 1,
      channel: 'whatsapp',
      label: 'WhatsApp',
      binary: 'agent-whatsapp',
      server: {
        defaultName: 'whatsapp',
        npxPackage: '@agentcomms/whatsapp',
        npxArgs: ['mcp'],
      },
      accounts: {
        map: 'accounts',
        noun: 'account',
        modes: ['read'],
        guarantee: {
          ceiling: 'code',
          floor: 'code',
          why: 'It reads only local files — a private copy of the store WhatsApp for Mac keeps on this Mac — and has no network client and no WhatsApp session, so it never sends: a draft is a link that opens WhatsApp with the text filled in, and the person presses send.',
        },
      },
      narrowing: [
        {
          option: 'account',
          flag: '--account',
          kind: 'pin',
        },
      ],
      rivals: {
        word: 'whatsapp',
        can: 'send WhatsApp messages as you',
      },
      hosts: [],
      approve: 'agent-whatsapp approve',
      skills: {
        prefix: 'whatsapp-',
        contract: 'skills/_shared/contract-whatsapp.md',
      },
      events: {
        types: ['whatsapp.message.received'],
        minimumIntervalMs: 60000,
        access: {
          kind: 'local-store',
        },
      },
    },
  },
];
