import { canonicalJson } from '../../json.ts';
import type { ObjectNode } from '../../schema/describe.ts';
import type { DefinitionInternal, ResendEmailReceivedV1, ResendEmailStatusChangedV1 } from '../types.ts';
import {
  ANY,
  address,
  array,
  common,
  dateTime,
  define,
  email,
  integer,
  nullableString,
  optional,
  riskFlags,
  string,
} from './shared.ts';

const account = /^acc_[A-Z0-9]{16}$/u;
const uuid = (): { kind: 'string'; format: 'uuid' } => ({ kind: 'string', format: 'uuid' });
const statuses = [
  'scheduled',
  'sent',
  'delivered',
  'delivery_delayed',
  'bounced',
  'complained',
  'opened',
  'clicked',
  'failed',
  'suppressed',
  'canceled',
  'queued',
] as const;

const receivedRoot: ObjectNode = {
  kind: 'object',
  properties: {
    ...common('resend.email.received', 'resend', account),
    emailId: uuid(),
    receivedAt: dateTime(),
    from: { kind: 'nullable', of: address() },
    replyTo: array(address()),
    to: array(email()),
    cc: array(email()),
    receivedFor: array(email()),
    subject: string(),
    messageId: nullableString(),
    attachmentCount: integer(),
    authentication: {
      kind: 'object',
      properties: {
        spf: nullableString(),
        dkim: nullableString(),
        dmarc: nullableString(),
        evaluatedBy: { kind: 'nullable', of: { kind: 'enum', values: ['resend'] } },
      },
    },
    attachments: optional(
      array({
        kind: 'object',
        properties: {
          id: { kind: 'string', minLength: 1 },
          filename: string(),
          contentType: nullableString(),
          size: { kind: 'nullable', of: integer() },
          inline: { kind: 'boolean' },
          riskFlags: riskFlags(),
        },
      }),
    ),
    body: optional({ kind: 'string', maxLength: 20000 }),
    bodyTruncated: optional({ kind: 'boolean' }),
  },
  dependentRequired: { body: ['bodyTruncated'], bodyTruncated: ['body'] },
};

export const resendEmailReceivedV1: DefinitionInternal<ResendEmailReceivedV1, Record<string, never>> = define<
  ResendEmailReceivedV1,
  Record<string, never>
>({
  type: 'resend.email.received',
  version: 1,
  channel: 'resend',
  description: receivedRoot,
  untrusted: [
    ['from', 'name'],
    ['replyTo', ANY, 'name'],
    ['subject'],
    ['attachments', ANY, 'filename'],
    ['attachments', ANY, 'contentType'],
    ['body'],
  ],
  content: [['from', 'name'], ['replyTo', ANY, 'name'], ['subject'], ['attachments', ANY, 'filename'], ['body']],
  addresses: [
    ['from', 'address'],
    ['replyTo', ANY, 'address'],
    ['to', ANY],
    ['cc', ANY],
    ['receivedFor', ANY],
  ],
  handles: [],
  formats: [
    { pattern: ['occurredAt'], format: 'date-time' },
    { pattern: ['observedAt'], format: 'date-time' },
    { pattern: ['receivedAt'], format: 'date-time' },
    { pattern: ['emailId'], format: 'uuid' },
    { pattern: ['from', 'address'], format: 'email' },
    { pattern: ['replyTo', ANY, 'address'], format: 'email' },
    { pattern: ['to', ANY], format: 'email' },
    { pattern: ['cc', ANY], format: 'email' },
    { pattern: ['receivedFor', ANY], format: 'email' },
  ],
  invariants: [
    { rule: 'sorted-utf8', pattern: ['attachments', ANY, 'riskFlags'] },
    { rule: 'same-instant', pointers: ['/receivedAt', '/occurredAt'] },
    { rule: 'length-equals', pointers: ['/attachments', '/attachmentCount'] },
  ],
  subject: (event) => event.emailId,
  dedupeKey: (event) => event.emailId,
  examples: [
    {
      id: '0123456789abcdef0123456789abcdef',
      type: 'resend.email.received',
      version: 1,
      occurredAt: '2026-10-07T12:00:00Z',
      observedAt: '2026-10-07T12:00:01Z',
      account: { name: 'Account', id: 'acc_ABCDEFGHIJKLMNOP', channel: 'resend' },
      emailId: '01234567-89ab-cdef-0123-456789abcdef',
      receivedAt: '2026-10-07T12:00:00Z',
      from: null,
      replyTo: [],
      to: ['recipient@example.com'],
      cc: [],
      receivedFor: [],
      subject: 'Subject',
      messageId: null,
      attachmentCount: 0,
      authentication: { spf: null, dkim: null, dmarc: null, evaluatedBy: null },
    },
    {
      id: 'fedcba9876543210fedcba9876543210',
      type: 'resend.email.received',
      version: 1,
      occurredAt: '2026-10-07T12:01:00Z',
      observedAt: '2026-10-07T12:01:01Z',
      account: { name: 'Account', id: 'acc_ABCDEFGHIJKLMNOP', channel: 'resend' },
      emailId: '12345678-89ab-cdef-0123-456789abcdef',
      receivedAt: '2026-10-07T12:01:00Z',
      from: { address: 'sender@example.com', name: 'Sender' },
      replyTo: [],
      to: ['recipient@example.com'],
      cc: [],
      receivedFor: [],
      subject: 'Subject',
      messageId: '<message@example.com>',
      attachmentCount: 1,
      authentication: { spf: 'pass', dkim: 'pass', dmarc: 'pass', evaluatedBy: 'resend' },
      attachments: [
        {
          id: 'attachment-1',
          filename: 'safe.svg',
          contentType: 'image/svg+xml',
          size: 1,
          inline: false,
          riskFlags: ['html-or-svg'],
        },
      ],
      body: 'Body',
      bodyTruncated: false,
    },
  ],
});

const statusRoot: ObjectNode = {
  kind: 'object',
  properties: {
    ...common('resend.email.status_changed', 'resend', account),
    emailId: uuid(),
    from: { kind: 'nullable', of: address() },
    to: array(email()),
    cc: array(email()),
    bcc: array(email()),
    subject: string(),
    createdAt: { kind: 'nullable', of: dateTime() },
    scheduledAt: { kind: 'nullable', of: dateTime() },
    messageId: nullableString(),
    previous: { kind: 'enum', values: statuses },
    current: { kind: 'enum', values: statuses },
    at: dateTime(),
  },
};

export const resendEmailStatusChangedV1: DefinitionInternal<ResendEmailStatusChangedV1, Record<string, never>> = define<
  ResendEmailStatusChangedV1,
  Record<string, never>
>({
  type: 'resend.email.status_changed',
  version: 1,
  channel: 'resend',
  description: statusRoot,
  untrusted: [['from', 'name'], ['subject']],
  content: [['from', 'name'], ['subject']],
  addresses: [
    ['from', 'address'],
    ['to', ANY],
    ['cc', ANY],
    ['bcc', ANY],
  ],
  handles: [],
  formats: [
    { pattern: ['occurredAt'], format: 'date-time' },
    { pattern: ['observedAt'], format: 'date-time' },
    { pattern: ['emailId'], format: 'uuid' },
    { pattern: ['from', 'address'], format: 'email' },
    { pattern: ['to', ANY], format: 'email' },
    { pattern: ['cc', ANY], format: 'email' },
    { pattern: ['bcc', ANY], format: 'email' },
    { pattern: ['createdAt'], format: 'date-time' },
    { pattern: ['scheduledAt'], format: 'date-time' },
    { pattern: ['at'], format: 'date-time' },
  ],
  invariants: [
    { rule: 'differs', pointers: ['/previous', '/current'] },
    { rule: 'identical', pointers: ['/at', '/occurredAt'] },
    { rule: 'identical', pointers: ['/occurredAt', '/observedAt'] },
  ],
  subject: (event) => event.emailId,
  dedupeKey: (event) => canonicalJson([event.emailId, event.previous, event.current, event.at]),
  examples: [
    {
      id: '0123456789abcdef0123456789abcdef',
      type: 'resend.email.status_changed',
      version: 1,
      occurredAt: '2026-10-07T12:00:00Z',
      observedAt: '2026-10-07T12:00:00Z',
      account: { name: 'Account', id: 'acc_ABCDEFGHIJKLMNOP', channel: 'resend' },
      emailId: '01234567-89ab-cdef-0123-456789abcdef',
      from: null,
      to: ['recipient@example.com'],
      cc: [],
      bcc: [],
      subject: 'Subject',
      createdAt: null,
      scheduledAt: null,
      messageId: null,
      previous: 'queued',
      current: 'sent',
      at: '2026-10-07T12:00:00Z',
    },
    {
      id: 'fedcba9876543210fedcba9876543210',
      type: 'resend.email.status_changed',
      version: 1,
      occurredAt: '2026-10-07T12:01:00Z',
      observedAt: '2026-10-07T12:01:00Z',
      account: { name: 'Account', id: 'acc_ABCDEFGHIJKLMNOP', channel: 'resend' },
      emailId: '12345678-89ab-cdef-0123-456789abcdef',
      from: { address: 'sender@example.com', name: 'Sender' },
      to: ['recipient@example.com'],
      cc: [],
      bcc: [],
      subject: 'Subject',
      createdAt: '2026-10-07T11:00:00Z',
      scheduledAt: null,
      messageId: '<message@example.com>',
      previous: 'sent',
      current: 'delivered',
      at: '2026-10-07T12:01:00Z',
    },
  ],
});
