#!/usr/bin/env node
/**
 * Keeps the generated parts of the skills in step with their sources.
 *
 * Three things drift if nobody watches them, and each has bitten a skill pack before: the shared contract diverging
 * between twelve copies, a skill that does not say where it fits, and a README whose descriptions no longer match
 * the frontmatter a client actually reads. All three are generated here and checked in CI, so a change to the one
 * source reaches every skill or the build fails.
 *
 * Run with `--check` to verify without writing, which is what CI does.
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SKILLS = join(ROOT, 'skills');
const CONTRACT = join(SKILLS, '_shared', 'contract.md');
const README = join(ROOT, 'README.md');
const check = process.argv.includes('--check');

const problems = [];
async function put(path, content) {
  let current = null;
  try {
    current = await readFile(path, 'utf8');
  } catch {
    // A file that does not exist yet is a difference like any other.
  }
  if (current === content) return;
  if (check) {
    problems.push(`${path.replace(ROOT, '')} is out of date — run \`pnpm sync:skills\``);
    return;
  }
  await mkdir(join(path, '..'), { recursive: true });
  await writeFile(path, content);
}

/** The frontmatter fields the README and the manifests are generated from. */
function frontmatter(source) {
  const block = /^---\n([\s\S]*?)\n---/.exec(source)?.[1] ?? '';
  const name = /^name:\s*(.+)$/m.exec(block)?.[1]?.trim() ?? '';
  const description = /^description:\s*"([\s\S]*?)"\s*$/m.exec(block)?.[1]?.trim() ?? '';
  return { name, description };
}

/**
 * The one line a routing file shows: the capability sentence, without the "Symptoms:" list.
 *
 * Taken from the description rather than written separately, so the two can never disagree — a routing line that
 * promises something the skill's own description does not is how a skill gets loaded for the wrong job.
 */
function useWhenFor(meta) {
  const first = meta.description.split(/\s+Symptoms:/)[0]?.trim() ?? meta.description.trim();
  return first.replace(/\s+/g, ' ');
}

const contract = await readFile(CONTRACT, 'utf8');
const names = (await readdir(SKILLS, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory() && entry.name.startsWith('gmail-'))
  .map((entry) => entry.name)
  .sort();

const rows = [];
for (const name of names) {
  const source = await readFile(join(SKILLS, name, 'SKILL.md'), 'utf8');
  const meta = frontmatter(source);
  if (!meta.name || !meta.description) {
    problems.push(`skills/${name}/SKILL.md: could not read its name and description from the frontmatter`);
    continue;
  }
  if (meta.name !== name) problems.push(`skills/${name}/SKILL.md: frontmatter name is "${meta.name}"`);
  rows.push(meta);

  // The contract, copied rather than linked: a skill is installed as a directory and a link out of it would break.
  await put(join(SKILLS, name, 'references', 'contract.md'), contract);
  // Where the skill fits. `requestOnly`: a mailbox is not a repository, so nothing in a codebase should ever
  // recommend these — they load when somebody asks for the job, and `useWhen` is the one line that says which job.
  await put(
    join(SKILLS, name, 'references', 'fit.json'),
    `${JSON.stringify({ kind: 'requestOnly', group: 'communications', useWhen: useWhenFor(meta) }, null, 2)}\n`,
  );
}

const table = [
  '<!-- generated by scripts/sync-skills.mjs — edit the skills, not this table -->',
  '| Skill | What it is for |',
  '|---|---|',
  ...rows.map((row) => `| [\`${row.name}\`](skills/${row.name}/SKILL.md) | ${row.description} |`),
  '<!-- end generated -->',
].join('\n');

const readme = await readFile(README, 'utf8');
const replaced = readme.replace(/<!-- generated by scripts\/sync-skills\.mjs[\s\S]*?<!-- end generated -->/, table);
if (replaced === readme && !readme.includes('<!-- end generated -->')) {
  problems.push('README.md has no generated skills block — add the marker comments');
} else {
  await put(README, replaced);
}

if (problems.length > 0) {
  for (const problem of problems) console.error(`- ${problem}`);
  process.exit(1);
}
console.log(`skills in step: ${rows.length} skills, contract copied, README table generated.`);
